language: go

os:
  - linux
  - osx

go:
  - tip
  - 1.12.x
  - 1.11.x

env:
  - GO111MODULE=on
 
install:
  - mkdir ./writers/rotate/testdata/

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

matrix:
  allow_failures:
    - go: tip
